name: assessors
channels:
  - conda-forge
  - pytorch

# These are our environment dependencies, which are pinned to versions compatible
# with the libraries defined in pyproject.toml, which mostly matters for the like 
# of tensorflow and torch.
# Everything we can, we manage with poetry.
# https://www.tensorflow.org/install/source#gpu
# You can build PyTorch from source with any CUDA version >=9.2 and 
# the binaries ship with the mentioned CUDA versions from the install selection.
# https://pytorch.org/get-started/locally/
dependencies:
  - python=3.9
  - pip=21.1
  - poetry=1.1
  - cudnn=8.1
  - cudatoolkit=11.3

  # We manage torch here, because we can't access torch+cu113 through poetry.
  # NOTE: This might give problems with dependencies (e.g. numpy) also being
  # managed by poetry.
  # https://github.com/python-poetry/poetry/issues/1391
  - pytorch=1.10
  - torchvision=0.11.2