[tool.poetry]
name        = "assessors"
version     = "0.1.0"
description = ""
authors     = ["Wout Schellaert <wout.schellaert@gmail.com>"]

[tool.poetry.dependencies]
python              = "^3.9"
tensorflow-gpu      = { version = "2.6.0rc2", allow-prereleases = true }
tensorflow-datasets = "^4.4.0"

[tool.poetry.dev-dependencies]
click      = "^8.0.1"
mypy       = "^0.910"
autopep8   = "^1.5.7"
pylint     = "^2.9.6"
jupyterlab = "^3.1.1"
ipykernel  = "^6.0.3"
nbdime     = "^3.1.0"
poethepoet = "^0.10.0"
wandb      = "^0.11.2"
Pillow     = "^8.3.1"  # Needed for wandb Image logging

[build-system]
requires      = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# https://github.com/nat-n/poethepoet
[tool.poe.tasks]
jpt   = { shell = "jupyter lab --no-browser --port=8888" }
mnist = { script = "experiments.mnist:main" }
cifar = { script = "experiments.cifar10:main" }
gpu   = { shell = "python scripts/gpu_test.py" }
